# Generated by Django 5.2.7 on 2025-11-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bot_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_bot_active',
            field=models.BooleanField(default=True),
        ),
    ]
