# Generated by Django 5.2.7 on 2025-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0002_contact_bot_disabled_at_contact_is_bot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
