# Generated by Django 5.2.7 on 2025-12-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0003_message_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10),
        ),
    ]
