# Generated by Django 5.2.7 on 2025-12-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0005_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=50),
        ),
    ]
