# Generated by Django 5.2.7 on 2025-12-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0007_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_intent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
