# Generated by Django 5.2.7 on 2025-12-29 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0008_contact_last_intent_contact_lead_score_contact_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('discovery', 'Descubrimiento'), ('engagement', 'Compromiso'), ('consideration', 'Consideración'), ('conversion', 'Conversión'), ('closed', 'Cerrado')], default='discovery', max_length=20)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('objection_count', models.IntegerField(default=0)),
                ('discount_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cart_items', models.JSONField(blank=True, default=list)),
                ('viewed_products', models.JSONField(blank=True, default=list)),
                ('preferred_category', models.CharField(blank=True, max_length=200)),
                ('last_objection_type', models.CharField(blank=True, max_length=50)),
                ('needs_human_handover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='botyapp.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(default='gemini-embedding-001', max_length=100)),
                ('search_text', models.TextField()),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['retailer_id'], name='botyapp_pro_retaile_16323d_idx'), models.Index(fields=['is_available', 'stock_quantity'], name='botyapp_pro_is_avai_9a8353_idx')],
            },
        ),
    ]
