# Generated by Django 5.2.7 on 2025-12-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0009_conversationstate_productembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='productembedding',
            name='image_embedding_vector',
            field=models.JSONField(blank=True, help_text='Embedding multimodal de la imagen del producto para identificación visual', null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('checkout_stage', models.CharField(choices=[('CONFIRMING_PRODUCT', 'Confirmando Producto'), ('COLLECTING_ADDRESS', 'Capturando Dirección'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('COMPLETED', 'Completado')], default='CONFIRMING_PRODUCT', max_length=30)),
                ('shipping_district', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_proof', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='botyapp.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=500)),
                ('product_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='botyapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botyapp.productembedding')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['contact', 'status'], name='botyapp_ord_contact_7131a0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='botyapp_ord_created_c11ceb_idx'),
        ),
    ]
