# Generated by Django 5.2.7 on 2025-12-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0010_productembedding_image_embedding_vector_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productembedding',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
