# Generated by Django 5.2.7 on 2025-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0011_productembedding_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='needs_human_attention',
            field=models.BooleanField(default=False),
        ),
    ]
