# Generated by Django 5.2.7 on 2026-01-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0013_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
