# Generated by Django 5.2.7 on 2026-01-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0014_order_stock_deducted_order_stock_deducted_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productembedding',
            name='botyapp_pro_is_avai_9a8353_idx',
        ),
        migrations.RemoveField(
            model_name='productembedding',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='productembedding',
            name='stock_l',
            field=models.IntegerField(default=0, verbose_name='Stock L'),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='stock_m',
            field=models.IntegerField(default=0, verbose_name='Stock M'),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='stock_s',
            field=models.IntegerField(default=0, verbose_name='Stock S'),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='stock_xl',
            field=models.IntegerField(default=0, verbose_name='Stock XL'),
        ),
        migrations.AddIndex(
            model_name='productembedding',
            index=models.Index(fields=['is_available'], name='botyapp_pro_is_avai_39a834_idx'),
        ),
    ]
