# Generated by Django 5.2.7 on 2026-01-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0016_rename_unit_price_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reverted',
            field=models.BooleanField(default=False),
        ),
    ]
