# Generated by Django 5.2.7 on 2026-01-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0017_order_stock_reverted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='current_state',
            field=models.CharField(choices=[('initial', 'Inicial'), ('browsing_catalog', 'Viendo Catálogo'), ('product_selection', 'Seleccionando Producto'), ('confirm_cart', 'Confirmando Carrito'), ('collect_address', 'Capturando Dirección'), ('select_payment', 'Eligiendo Pago'), ('upload_proof', 'Subiendo Comprobante'), ('completed', 'Completado'), ('locked_human', 'Soporte Humano (Bloqueado)')], default='initial', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='flow_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
