# Generated by Django 5.2.7 on 2026-01-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0018_contact_current_state_contact_flow_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROFORMA', 'Proforma (Cotización)'), ('PENDING', 'Pendiente'), ('PENDING_SIZE', 'Pendiente - Sin Talla'), ('CONFIRMED', 'Confirmado'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
