# Generated by Django 5.2.7 on 2026-01-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botyapp', '0020_ownernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownernotification',
            name='notification_type',
            field=models.CharField(choices=[('handoff', 'Handoff / Asesor'), ('system', 'Sistema'), ('order', 'Nuevo Pedido')], default='system', max_length=20),
        ),
    ]
