services:
  # Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shurumbadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shurumbapass
    ports:
      - "5432:5432" # Exponer puerto interno 5432 al externo 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio del Bot (Django)
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env # <--- AQUÍ ESTÁ EL CAMBIO: Busca el .env un nivel arriba
    environment:
      - DEBUG=1
      # Override de la DB para usar la interna de Docker en lugar de la que esté en .env
      - DATABASE_URL=postgres://postgres:shurumbapass@db:5432/shurumbadb
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
