# Generated by Django 5.2.7 on 2025-10-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='color',
            field=models.CharField(default='Rojo', max_length=255),
        ),
        migrations.AddField(
            model_name='catalog',
            name='size',
            field=models.CharField(default='S', max_length=255),
        ),
    ]
