# Generated by Django 5.2.7 on 2025-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0002_catalog_color_catalog_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Talla de Producto',
                'verbose_name_plural': 'Tallas de Productos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='size',
        ),
        migrations.AddField(
            model_name='catalog',
            name='tallas',
            field=models.ManyToManyField(related_name='prendas', to='catalogo_app.talla'),
        ),
    ]
