# Generated by Django 5.2.7 on 2025-10-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0003_talla_remove_catalog_size_catalog_tallas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Talla',
        ),
    ]
